version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: noyo/address-history-challenge
    ports:
      - "27606:27606"
    environment:
      - DATABASE_DATABASE=app_db
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
    links:
      - db

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
